apiVersion: v1
data:
  application.properties: |
    spring.application.name= users-service
    spring.datasource.url = jdbc:mysql://auth-mysql8:3306/authentication
    spring.datasource.username = root
    spring.datasource.password = auth
    spring.jpa.show-sql = true
    spring.jpa.hibernate.ddl-auto = update
    spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQL5Dialect
    server.port=8085
    spring.jpa.properties.hibernate.jdbc.time_zone=UTC
kind: ConfigMap
metadata:
  creationTimestamp: "2020-01-14T14:34:17Z"
  name: users-service
  namespace: default
  resourceVersion: "44530"
  selfLink: /api/v1/namespaces/default/configmaps/users-service
  uid: f1e0b509-36da-11ea-afdc-00155d579305